In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

plt.rcParams["figure.figsize"] = (12,6)

# NumPy

**Задача 1**\
Сгенерировать массив из случайных положительных чисел произвольной длины. Вывести элементы, которые больше среднего арифметического.

In [2]:
arr = np.random.randint(0,10000,size=20)
arr_mean = np.mean(arr)
arr[arr > arr_mean]

array([5944, 6552, 7432, 9617, 7388, 6401, 9853, 5993, 5458, 6554])

**Задача 2**\
Сгенерировать массив из 20 случайных элементов, элементы которого лежат в интервале [0, 10].
+ Определить количество элементов, отличающихся от минимального на 5.
+ Найти среднее арифметическое всех четных элементов массива, стоящих на нечетных местах.

In [3]:
arr_2 = np.random.randint(0,11,size=20)
arr_2

array([10, 10,  1,  2,  5,  5,  4,  2,  1,  6,  2,  4,  6,  5,  6,  9,  1,
        3, 10,  6])

In [4]:
arr_2_min = np.min(arr_2)
cond = arr_2 == arr_2_min + 5
arr_2[cond].shape[0]

4

In [5]:
arr2_slice = arr_2[1::2]
cond = arr2_slice % 2 == 0
np.mean(arr2_slice[cond])

5.0

**Задача 3**\
Сгенерировать матрицу A размером 5 на 5, элементы которой лежат в интервале [1, 10].
+ Возвести в квадрат максимальный элемент матрицы.
+ Все четные числа заменить на 0.

In [6]:
matrix_a = np.random.randint(0,11,size=(5,5))
matrix_a 

array([[ 0,  5,  7,  1,  2],
       [ 7, 10,  3,  0,  4],
       [ 2,  9,  3,  0,  8],
       [ 6,  0, 10, 10,  6],
       [ 3,  7,  7,  0,  8]])

In [7]:
matrix_a_max = np.max(matrix_a)
sq_matrix_a_max = matrix_a_max ** 2
sq_matrix_a_max

100

In [8]:
matrix_a[matrix_a % 2 == 0] = 0
matrix_a

array([[0, 5, 7, 1, 0],
       [7, 0, 3, 0, 0],
       [0, 9, 3, 0, 0],
       [0, 0, 0, 0, 0],
       [3, 7, 7, 0, 0]])

**Задача 4**\
Сгенерировать матрицу B размером 5 на 5, элементы которой лежат в интервале [-5, 5]. Отрицательные элементы матрицы заменить на число отрицательных элементов в строке, в которой они находятся.

In [9]:
matrix_b = np.random.randint(-5,5,size=(5,5))
matrix_b

array([[-4,  3, -2,  4, -1],
       [-5, -5, -3, -4,  1],
       [ 4,  1,  3,  0, -4],
       [ 1,  4, -5,  0,  4],
       [-4, -2,  3,  4, -4]])

In [10]:
for i in range(matrix_b.shape[0]):
    matrix_b[i][matrix_b[i] < 0] = matrix_b[i][matrix_b[i] < 0].shape[0]
matrix_b

array([[3, 3, 3, 4, 3],
       [4, 4, 4, 4, 1],
       [4, 1, 3, 0, 1],
       [1, 4, 1, 0, 4],
       [3, 3, 3, 4, 3]])

# Pandas

In [11]:
df = pd.read_csv("https://raw.githubusercontent.com/rolandmueller/titanic/main/titanic3.csv")
df.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [12]:
df.shape

(1309, 14)

**Задание 1**
+ Какой была максимальная цена билета? Медиана?
+ Какова доля выживших?
+ Сколько мужчин / женщин находилось на борту?

In [13]:
price_max = df['fare'].max()
price_median = df['fare'].median()

print(f'Максимальная цена билета: {price_max}')
print(f'Медианная цена билета: {price_median}')

Максимальная цена билета: 512.3292
Медианная цена билета: 14.4542


In [14]:
survived_sum = df['survived'].sum()
survivers_percentage = survived_sum/df.shape[0] * 100
print(f'Доля выживших: {survivers_percentage.round(2)}%')

Доля выживших: 38.2%


In [15]:
df['sex'].value_counts()

sex
male      843
female    466
Name: count, dtype: int64

**Задание 2**
+ Выведите распределение переменной __pclass__ для мужчин и женщин.
    + Сколько мужчин было в первом классе?
    + Сколько женщин было в третьем классе?
      
+ Создайте новый признак __age_group__, который равен:
    + 1, если пассажир был моложе 30 лет;
    + 2, если пассажиру было от 30 до 60 лет;
    + 3, если пассажир был старше 60 лет.

In [16]:
pd.pivot_table(data = df,
               values = 'name',
               index = 'pclass',
               columns = 'sex',
              aggfunc = 'count')

sex     female  male
pclass              
1          144   179
2          106   171
3          216   493

In [17]:
n_first_class_men = df.loc[(df['sex']=='male') & (df['pclass']== 1)].shape[0]
n_third_class_women = df.loc[(df['sex']=='female') & (df['pclass']== 3)].shape[0]


print(f'Количество мужчин в первом классе: {n_first_class_men}')
print(f'Количество женщин в третьем классе: {n_third_class_women}')

Количество мужчин в первом классе: 179
Количество женщин в третьем классе: 216


In [18]:
def age_group(age):
    if age < 30: 
        return 1
    elif age >= 30 and age <= 60:
        return 2
    elif age > 60:
        return 3

df['age_group'] = df['age'].apply(age_group)
df.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  age_group  
0                     St Louis, MO        1.0  
1  Montreal, PQ / Chesterville, ON        1.0  
2  Montreal, PQ / Chesterville, ON        1.0  
3  Montreal, PQ / Chesterville, ON        2.0  
4  Montreal, PQ / Chesterville, ON        1.0

In [19]:
df[df['name'].str.contains(r'Charles', case=False, na=False)]

pclass  survived                                               name  \
97         1         1  Douglas, Mrs. Frederick Charles (Mary Helene B...   
114        1         0                     Fortune, Mr. Charles Alexander   
147        1         0                          Harrington, Mr. Charles H   
154        1         0                         Hays, Mr. Charles Melville   
155        1         1  Hays, Mrs. Charles Melville (Clara Jennings Gr...   
171        1         0                         Jones, Mr. Charles Cresson   
212        1         0                              Natsch, Mr. Charles H   
240        1         1      Romaine, Mr. Charles Hallace ("Mr C Rolmane")   
280        1         1                    Stengel, Mr. Charles Emil Henry   
281        1         1  Stengel, Mrs. Charles Emil Henry (Annie May Mo...   
316        1         0                        Williams, Mr. Charles Duane   
325        2         0                     Aldworth, Mr. Charles Augustus   
332        2         0                     Baimbrigge, Mr. Charles Robert   
367        2         0                         Chapman, Mr. Charles Henry   
372        2         0                      Clarke, Mr. Charles Valentine   
373        2         1        Clarke, Mrs. Charles V (Ada Maria Winfield)   
374        2         0                    Coleridge, Mr. Reginald Charles   
386        2         0                          Davies, Mr. Charles Henry   
408        2         0                      Fillbrook, Mr. Joseph Charles   
472        2         0                     Kirkland, Rev. Charles Leonard   
488        2         0                       Louch, Mr. Charles Alexander   
489        2         1  Louch, Mrs. Charles Alexander (Alice Adelaide ...   
510        2         0                           Mudd, Mr. Thomas Charles   
518        2         0                       Nicholls, Mr. Joseph Charles   
542        2         1      Quick, Mrs. Frederick Charles (Jane Richards)   
555        2         0         Sedgwick, Mr. Charles Frederick Waddington   
596        2         1                              Wilhelms, Mr. Charles   
597        2         1                       Williams, Mr. Charles Eugene   
645        3         1                         Asplund, Mr. Johan Charles   
704        3         0                           Cann, Mr. Ernest Charles   
813        3         0             Franklin, Mr. Charles (Charles Fardon)   
830        3         0                        Goodwin, Mr. Charles Edward   
831        3         0                     Goodwin, Mr. Charles Frederick   
1027       3         0                         Moore, Mr. Leonard Charles   
1192       3         0                      Sawyer, Mr. Frederick Charles   
1199       3         0                        Shorney, Mr. Charles Joseph   
1241       3         0                              Thomas, Mr. Charles P   
1283       3         0                        Warren, Mr. Charles William   
1287       3         0                   Widegren, Mr. Carl/Charles Peter   

         sex   age  sibsp  parch              ticket      fare        cabin  \
97    female  27.0      1      1            PC 17558  247.5208      B58 B60   
114     male  19.0      3      2               19950  263.0000  C23 C25 C27   
147     male   NaN      0      0              113796   42.4000          NaN   
154     male  55.0      1      1               12749   93.5000          B69   
155   female  52.0      1      1               12749   93.5000          B69   
171     male  46.0      0      0                 694   26.0000          NaN   
212     male  37.0      0      1            PC 17596   29.7000         C118   
240     male  45.0      0      0              111428   26.5500          NaN   
280     male  54.0      1      0               11778   55.4417         C116   
281   female  43.0      1      0               11778   55.4417         C116   
316     male  51.0      0      1            PC 17597   6

**Задание 3**\
Найдите самое популярное имя среди пассажиров:
+ мужчин;
+ женщин.

In [20]:
status_list = df['name'].str.split().str[1].unique()
def split_cond(name):
    if 'Mrs'in name and '(' in name and ')' in name:
        return name.split('(')[1].split(')')[0].strip()
    else:
        for status in status_list:
            if status in name:
                return name.split(status)[1].strip().split(' ')[0]
    return name.strip().split()[0]

In [21]:
df['name_only'] = df['name'].apply(split_cond)
df.groupby('sex')['name_only'].value_counts().groupby(level=0).head(1)

sex     name_only
female  Mary         12
male    William      50
Name: count, dtype: int64

**Задание 4**
+ Выведите данные о всех пассажирах, которые сели в Cherbourg (Embarked='C') и были старше 50 лет.
+ Выведите данные о всех женщинах младше 20 и старше 50 лет.
+ Сколько пассажиров старше 70 лет было на борту?

In [22]:
df.query('embarked == "C" and age > 50')

pclass  survived                                               name  \
9         1         0                            Artagaveytia, Mr. Ramon   
43        1         1    Bucknell, Mrs. William Robert (Emma Eliza Ward)   
48        1         1   Candee, Mrs. Edward (Helen Churchill Hungerford)   
50        1         1  Cardeza, Mrs. James Warburton Martinez (Charlo...   
78        1         1  Compton, Mrs. Alexander Taylor (Mary Eliza Ing...   
104       1         1                     Eustis, Miss. Elizabeth Mussey   
123       1         1                   Frolicher-Stehli, Mr. Maxmillian   
135       1         0                          Goldschmidt, Mr. George B   
136       1         1                          Gracie, Col. Archibald IV   
174       1         0                            Kent, Mr. Edward Austin   
186       1         1          Lindstrom, Mrs. Carl Johan (Sigrid Posse)   
192       1         1                               Lurette, Miss. Elise   
215       1         0                         Newell, Mr. Arthur Webster   
221       1         0                     Ostby, Mr. Engelhart Cornelius   
233       1         1      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)   
246       1         0                             Rothschild, Mr. Martin   
247       1         1     Rothschild, Mrs. Martin (Elizabeth L. Barrett)   
252       1         0                         Ryerson, Mr. Arthur Larned   
264       1         1                Simonius-Blumer, Col. Oberst Alfons   
267       1         0                            Smith, Mr. James Clinch   
276       1         0                      Spencer, Mr. William Augustus   
280       1         1                    Stengel, Mr. Charles Emil Henry   
282       1         1    Stephenson, Mrs. Walter Bertram (Martha Eustis)   
303       1         0                           Warren, Mr. Frank Manley   
304       1         1   Warren, Mrs. Frank Manley (Anna Sophia Atkinson)   
308       1         1              White, Mrs. John Stuart (Ella Holmes)   
316       1         0                        Williams, Mr. Charles Duane   

        sex   age  sibsp  parch    ticket      fare            cabin embarked  \
9      male  71.0      0      0  PC 17609   49.5042              NaN        C   
43   female  60.0      0      0     11813   76.2917              D15        C   
48   female  53.0      0      0  PC 17606   27.4458              NaN        C   
50   female  58.0      0      1  PC 17755  512.3292      B51 B53 B55        C   
78   female  64.0      0      2  PC 17756   83.1583              E45        C   
104  female  54.0      1      0     36947   78.2667              D20        C   
123    male  60.0      1      1     13567   79.2000              B41        C   
135    male  71.0      0      0  PC 17754   34.6542               A5        C   
136    male  53.0      0      0    113780   28.5000              C51        C   
174    male  58.0      0      0     11771   29.7000              B37        C   
186  female  55.0      0      0    112377   27.7208              NaN        C   
192  female  58.0      0      0  PC 17569  146.5208              B80        C   
215    male  58.0      0      2     35273  113.2750              D48        C   
221    male  65.0      0      1    113509   61.9792              B30        C   
233  female  56.0      0      1     11767   83.1583              C50        C   
246    male  55.0      1      0  PC 17603   59.4000              NaN        C   
247  female  54.0      1      0  PC 17603   59.4000              NaN        C   
252    male  61.0      1      3  PC 17608  262.3750  B57 B59 B63 B66        C   
264    male  56.0      0      0     13213   35.5000              A26        C   
267    male  56.0      0      0     17764   30.6958               A7        C   
276    male  57.0      1      0  PC 17569  146.5208              B78        C   
280    male  54.0      1      0     11778   55.4417             C116        C   
282  female  

In [23]:
df.query('sex == "female" and (age < 20 or age > 50)')

pclass  survived                                               name  \
2          1         0                       Allison, Miss. Helen Loraine   
6          1         1                  Andrews, Miss. Kornelia Theodosia   
8          1         1      Appleton, Mrs. Edward Dale (Charlotte Lamson)   
11         1         1  Astor, Mrs. John Jacob (Madeleine Talmadge Force)   
27         1         1            Bishop, Mrs. Dickinson H (Helen Walton)   
...      ...       ...                                                ...   
1265       3         0                          Van Impe, Miss. Catharina   
1273       3         0                 Vander Planke, Miss. Augusta Maria   
1279       3         0               Vestrom, Miss. Hulda Amanda Adolfina   
1300       3         1            Yasbeck, Mrs. Antoni (Selini Alexander)   
1304       3         0                               Zabour, Miss. Hileni   

         sex   age  sibsp  parch    ticket      fare    cabin embarked boat  \
2     female   2.0      1      2    113781  151.5500  C22 C26        S  NaN   
6     female  63.0      1      0     13502   77.9583       D7        S   10   
8     female  53.0      2      0     11769   51.4792     C101        S    D   
11    female  18.0      1      0  PC 17757  227.5250  C62 C64        C    4   
27    female  19.0      1      0     11967   91.0792      B49        C    7   
...      ...   ...    ...    ...       ...       ...      ...      ...  ...   
1265  female  10.0      0      2    345773   24.1500      NaN        S  NaN   
1273  female  18.0      2      0    345764   18.0000      NaN        S  NaN   
1279  female  14.0      0      0    350406    7.8542      NaN        S  NaN   
1300  female  15.0      1      0      2659   14.4542      NaN        C  NaN   
1304  female  14.5      1      0      2665   14.4542      NaN        C  NaN   

       body                        home.dest  age_group  \
2       NaN  Montreal, PQ / Chesterville, ON        1.0   
6       NaN                       Hudson, NY        3.0   
8       NaN              Bayside, Queens, NY        2.0   
11      NaN                     New York, NY        1.0   
27      NaN                     Dowagiac, MI        1.0   
...     ...                              ...        ...   
1265    NaN                              NaN        1.0   
1273    NaN                              NaN        1.0   
1279    NaN                              NaN        1.0   
1300    NaN                              NaN        1.0   
1304  328.0                              NaN        1.0   

                     name_only  
2                        Helen  
6                     Kornelia  
8             Charlotte Lamson  
11    Madeleine Talmadge Force  
27                Helen Walton  
...                        ...  
1265                 Catharina  
1273                   Augusta  
1279                     Hulda  
1300          Selini Alexander  
1304                    Hileni  

[135 rows x 16 columns]

In [24]:
df.query('age > 70').shape[0]

6

**Задание 5**
+ Посчитайте средний возраст среди мужчин и среди женщин.
+ Посчитайте доли выживших в различных возрастных группах (новый признак **AgeGroup**).
+ Найдите максимальную стоимость билета в каждом из ценовых классов.

In [25]:
mean_male_age = df.loc[df['sex']=='male','age'].mean()
mean_female_age =df.loc[df['sex']=='female','age'].mean()

print(f'Средний возраст мужчин: {mean_male_age.round(2)}')
print(f'Средний возраст женщин: {mean_female_age.round(2)}')

Средний возраст мужчин: 30.59
Средний возраст женщин: 28.69


In [26]:
df.groupby('age_group')['survived'].agg('sum')/df.groupby('age_group')['survived'].agg('count')

age_group
1.0    0.409490
2.0    0.418919
3.0    0.242424
Name: survived, dtype: float64

In [27]:
df.groupby('pclass')['fare'].agg('max')

pclass
1    512.3292
2     73.5000
3     69.5500
Name: fare, dtype: float64

**Задание 6**\
Ответьте на предыдущие вопросы с помощью функции crosstab и метода pivot_table.

In [29]:
pd.pivot_table(data = df,
            values = 'age',
            index = 'sex',
            aggfunc = 'mean')

age
sex              
female  28.687071
male    30.585233

In [36]:
pd.pivot_table(data = df,
            values = 'survived',
            index = 'age_group')

survived
age_group          
1.0        0.409490
2.0        0.418919
3.0        0.242424

In [37]:
pd.pivot_table(data = df,
            values = 'fare',
            index = 'pclass',
            aggfunc = 'max')

fare
pclass          
1       512.3292
2        73.5000
3        69.5500